#pragma once

enum {
    RC_SUCCESS = 0,
    RC_INVALID_NUMBER,
    RC_EXPECTED_NUMBER,
    RC_ERR_UNABLE_TO_ALLOC,
    RC_ERR_INVALID_VAR_INDEX,
    RC_ERR_VAR_NOT_DEFINED,

    MIN_NUMBER = 1,
    MAX_NUMBER = 256,
};