#pragma once

enum {
    RC_ERR_PLACEHOLDER = -1,
    RC_SUCCESS = 0,
    RC_INVALID_NUMBER,
    RC_EXPECTED_NUMBER,
    RC_ERR_UNABLE_TO_ALLOC,
    RC_ERR_INVALID_VAR_INDEX,
    RC_ERR_VAR_NOT_DEFINED,
    RC_ERR_INVALID_NUMBER,
    RC_ERR_EXPECTED_NUMBER,
    RC_ERR_EXPECTED_LPAREN,
    RC_ERR_EXPECTED_RPAREN,
    RC_ERR_EXPECTED_EXPR,
    RC_ERR_EXPECTED_STATEMENT,
    RC_ERR_EXPECTED_VARIABLE,
    RC_ERR_EXPECTED_EQUAL,
    RC_ERR_EXPECTED_NEWLINE,
    RC_ERR_EXPECTED_RELOP,
    RC_ERR_EXPECTED_THEN,
    RC_BYE,
    RC_ERR_ILLEGAL_DIRECT,
    RC_ERR_ILLEGAL_INDIRECT,
    RC_ERR_STACK_OVERFLOW,
    RC_ERR_STACK_UNDERFLOW,
    RC_ERR_LINE_NUM_TOO_BIG,

    RC_ERR_INPUT_STRLEN_EXCEEDED,
    RC_ERR_UNABLE_TO_GETLINE,
    RC_ERR_INPUT_TOO_BIG,

    MIN_NUMBER = 1,
    MAX_NUMBER = 256,
};

enum { 
    MAX_BUFFER_SIZE = 80,
    MAX_INPUT_SIZE = 72,
    MAX_INPUT_STRLEN = MAX_BUFFER_SIZE -1,
};