#pragma once

enum {
    RC_ERR_PLACEHOLDER = -1,
    RC_SUCCESS = 0,
    RC_INVALID_NUMBER,
    RC_EXPECTED_NUMBER,
    RC_ERR_UNABLE_TO_ALLOC,
    RC_ERR_INVALID_VAR_INDEX,
    RC_ERR_VAR_NOT_DEFINED,
    RC_ERR_INVALID_NUMBER,
    RC_ERR_EXPECTED_NUMBER,
    RC_ERR_EXPECTED_LPAREN,
    RC_ERR_EXPECTED_RPAREN,
    RC_ERR_EXPECTED_EXPR,

    RC_ERR_INPUT_STRLEN_EXCEEDED,
    RC_ERR_UNABLE_TO_GETLINE,

    MIN_NUMBER = 1,
    MAX_NUMBER = 256,
};